### ISSUE TITLE
Archive?

### ISSUE THREAD

**Issue by oschwald** [maxmind/App-CISetup#10]
With the recent Travis changes, the appeal of this module seems rather limited. Does anyone object to archiving it or, alternatively, want to take it over?

@autarch @2shortplanks?

**Comment by autarch** [comment]
No objections from me. I'm moving all my stuff to Azure (and then maybe again to GitHub Actions once I port my helpers).

**Comment by 2shortplanks** [comment]
I’m using CircleCI these days. Archive away!

**Comment by oschwald** [comment]
Thanks! Archiving.
