### ISSUE TITLE
Maybe it's time to retire "sudo: false" on Travis?

### ISSUE THREAD

**Issue by oalders** [maxmind/App-CISetup#6]
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

**Comment by autarch** [comment]
Already done - https://metacpan.org/changes/distribution/App-CISetup

**Comment by oalders** [comment]
Ah, OK.  It confused me to see it still in the docs: https://metacpan.org/pod/release/DROLSKY/App-CISetup-0.16/bin/setup-travis-yml.pl#sudo-and-addons

**Comment by autarch** [comment]
Oops, thanks for the pointer. I removed this.
